### ISSUE TITLE
Incomplete Simplifications on `encoding`

### ISSUE THREAD

**Issue by julianayang777** [formalsec/whilloc#21]
Some simplifications of expressions are not simplified at all. 
Examples:
```
(int.add (int.add $_descending 3) 10) = (int.add $_descending 13)
(int.add (int.add (int.add $_descending 3) 10) 1)  = (int.add $_descending 14)
(bool.ite (bool.and true true) 5 0) = 5
```

_Originally posted by @filipeom in https://github.com/formalsec/whilloc/pull/19#discussion_r1528763384_
_Originally posted by @filipeom in https://github.com/formalsec/whilloc/pull/19#discussion_r1528766052_

**Comment by joaomhmpereira** [comment]
Related to https://github.com/formalsec/encoding/issues/95
